Repository codesquad-member-2020/issue-tracker-06, pull requests merged in 2020-06, with the labels that each got.

#10 [FE] 개발환경구성
  FE/.gitignore
  FE/.prettierrc
  FE/babel.config.js
  FE/package-lock.json
  FE/package.json
  FE/webpack.common.js
  FE/webpack.config.js
  FE/webpack.dev.js
  FE/webpack.prod.js
Labels: FE, feature

#11 [FE] 설계한 컴포넌트 파일 생성
  FE/src/App.jsx
  FE/src/Issue/Filters/Filters.jsx
  FE/src/Issue/Issue.jsx
  FE/src/Issue/List/List.jsx
  FE/src/IssueDetail/IssueContent/IssueContent.jsx
  FE/src/IssueDetail/IssueDetail.jsx
  FE/src/IssueDetail/IssueWrite/IssueWrite.jsx
  FE/src/IssueInfo/IssueInfo.jsx
  FE/src/Labels/Labels.jsx
  FE/src/Labels/NewLabel/NewLabel.jsx
  FE/src/LabelsMilestoneTap/LabelsMilestoneTap.jsx
  FE/src/Main/Login/Login.jsx
  FE/src/Main/Main.jsx
  FE/src/Milestone/Milestone.jsx
  FE/src/Milestone/MilestoneDetail/MilestoneDetail.jsx
  FE/src/Milestone/MilestoneInfo/MilestoneInfo.jsx
  FE/src/Modal/Modal.jsx
  FE/src/NewIssue/NewIssue.jsx
  FE/src/NewMilestone/NewMilestone.jsx
  FE/src/index.jsx
Labels: FE, feature

#12 [BE] 프로젝트 세팅
  be/.gitignore
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/com/codesquad/issue/IssueApplication.java
  be/src/main/resources/application.properties
  be/src/main/resources/schema.sql
  be/src/test/java/com/codesquad/issue/IssueApplicationTests.java
Labels: BE

#17 [FE] UI 구현
  FE/.gitignore
  FE/package-lock.json
  FE/package.json
  FE/src/App.jsx
  FE/src/Issue/Filters/Filters.jsx
  FE/src/Issue/Issue.jsx
  FE/src/Issue/List/List.jsx
  FE/src/Labels/Labels.jsx
  FE/src/Labels/NewLabel/NewLabel.jsx
  FE/src/LabelsMilestoneTap/LabelsMilestoneTap.jsx
  FE/src/Milestone/Milestone.jsx
  FE/src/Milestone/MilestoneDetail/MilestoneDetail.jsx
  FE/src/Milestone/MilestoneInfo/MilestoneInfo.jsx
  FE/src/NewMilestone/NewMilestone.jsx
  FE/src/components/Issue/Filters/Filters.jsx
  FE/src/components/Issue/Issue.jsx
  FE/src/components/Issue/List/List.jsx
  FE/src/components/IssueDetail/IssueContent/IssueContent.jsx
  FE/src/components/IssueDetail/IssueDetail.jsx
  FE/src/components/IssueDetail/IssueWrite/IssueWrite.jsx
  FE/src/components/IssueInfo/IssueInfo.jsx
  FE/src/components/Labels/Labels.jsx
  FE/src/components/Labels/NewLabel/NewLabel.jsx
  FE/src/components/LabelsMilestonesTap/LabelsMilestonesTap.jsx
  FE/src/components/Layout/Wrap.jsx
  FE/src/components/Main/Login/Login.jsx
  FE/src/components/Main/Main.jsx
  FE/src/components/Milestones/MilestoneDetail/MilestoneDetail.jsx
  FE/src/components/Milestones/MilestoneInfo/MilestoneInfo.jsx
  FE/src/components/Milestones/Milestones.jsx
  FE/src/components/Modal/Modal.jsx
  FE/src/components/NewIssue/NewIssue.jsx
  FE/src/components/NewMilestone/NewMilestone.jsx
  FE/src/components/header/Header.jsx
  FE/src/components/style/GlobalStyle.jsx
  FE/src/components/style/theme.jsx
  FE/webpack.common.js
Labels: ✨feature✨, 💕FE💕

#18 [FE] 라우팅 설정
  FE/src/App.jsx
Labels: ✨feature✨, 💕FE💕

#20 [BE] 프로젝트 및 DB 설정
  be/.gitignore
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/com/codesquad/issue/IssueApplication.java
  be/src/main/resources/application-dev.properties
  be/src/main/resources/application-local.properties
  be/src/main/resources/application.properties
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  be/src/test/java/com/codesquad/issue/IssueApplicationTests.java
Labels: 🙉BE

#21 [BE] Spring REST Docs 테스트
  be/src/docs/asciidoc/api-docs.adoc
  be/src/main/java/com/codesquad/issue/controller/IssueController.java
  be/src/main/java/com/codesquad/issue/dto/UserDTO.java
  be/src/test/java/com/codesquad/issue/controller/IssueControllerTest.java
Labels: 🙉BE

#22 [BE] Test 실행시 dev 환경으로 설정하도록 수정
  be/src/main/resources/application.properties
Labels: 🙉BE

#27 [BE] 필터로 이슈 가져오기
  be/src/docs/asciidoc/api-docs.adoc
  be/src/main/java/com/codesquad/issue/application/IssueService.java
  be/src/main/java/com/codesquad/issue/controller/IssueController.java
  be/src/main/java/com/codesquad/issue/domain/IssueDAO.java
  be/src/main/java/com/codesquad/issue/dto/IssueOverviewDTO.java
  be/src/main/java/com/codesquad/issue/dto/IssueOverviewListDTO.java
  be/src/main/java/com/codesquad/issue/dto/LabelDTO.java
  be/src/main/java/com/codesquad/issue/dto/UserDTO.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  be/src/test/java/com/codesquad/issue/application/IssueServiceTest.java
  be/src/test/java/com/codesquad/issue/controller/IssueControllerTest.java
Labels: ✨feature✨, 🙉BE

#28 [BE] github oauth 추가
  be/build.gradle
  be/src/main/java/com/codesquad/issue/application/LoginService.java
  be/src/main/java/com/codesquad/issue/common/JwtInterceptor.java
  be/src/main/java/com/codesquad/issue/common/WebConfig.java
  be/src/main/java/com/codesquad/issue/controller/LoginController.java
  be/src/main/java/com/codesquad/issue/domain/GithubProperties.java
  be/src/main/java/com/codesquad/issue/domain/JwtProperties.java
  be/src/main/java/com/codesquad/issue/domain/User.java
  be/src/main/java/com/codesquad/issue/domain/UserDAO.java
  be/src/main/java/com/codesquad/issue/exception/UnauthorizedException.java
  be/src/main/java/com/codesquad/issue/util/JwtUtil.java
Labels: ✨feature✨, 🙉BE

#30 [BE] IssueListDTO에 필터 관련 필드 추가
  be/src/docs/asciidoc/api-docs.adoc
  be/src/main/java/com/codesquad/issue/application/IssueService.java
  be/src/main/java/com/codesquad/issue/common/JwtInterceptor.java
  be/src/main/java/com/codesquad/issue/domain/IssueDAO.java
  be/src/main/java/com/codesquad/issue/domain/LabelDAO.java
  be/src/main/java/com/codesquad/issue/domain/MilestoneDAO.java
  be/src/main/java/com/codesquad/issue/domain/UserDAO.java
  be/src/main/java/com/codesquad/issue/dto/IssueOverviewListDTO.java
  be/src/main/java/com/codesquad/issue/dto/MilestoneDTO.java
  be/src/test/java/com/codesquad/issue/application/IssueServiceTest.java
  be/src/test/java/com/codesquad/issue/application/UserServiceTest.java
  be/src/test/java/com/codesquad/issue/controller/IssueControllerTest.java
Labels: ✨feature✨, 🙉BE

#32 [BE] 이슈 추가
  be/src/docs/asciidoc/api-docs.adoc
  be/src/main/java/com/codesquad/issue/application/IssueService.java
  be/src/main/java/com/codesquad/issue/controller/IssueController.java
  be/src/main/java/com/codesquad/issue/domain/IssueDAO.java
  be/src/main/java/com/codesquad/issue/domain/LabelDAO.java
  be/src/main/java/com/codesquad/issue/domain/RequestIssue.java
  be/src/main/java/com/codesquad/issue/domain/UserDAO.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  be/src/test/java/com/codesquad/issue/controller/IssueControllerTest.java
Labels: ✨feature✨, 🙉BE
